// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    GlobalCodeBox: typeof import('./src/components/global/GlobalCodeBox.vue')['default']
    GlobalCodeSandbox: typeof import('./src/components/global/GlobalCodeSandbox.vue')['default']
    GlobalColors: typeof import('./src/components/global/GlobalColors.vue')['default']
    GlobalGap: typeof import('./src/components/global/GlobalGap.vue')['default']
    Home: typeof import('./src/components/views/home/Home.vue')['default']
    LayoutFooter: typeof import('./src/components/layout/footer/LayoutFooter.vue')['default']
    LayoutFooterCol: typeof import('./src/components/layout/footer/LayoutFooterCol.vue')['default']
    LayoutFooterItem: typeof import('./src/components/layout/footer/LayoutFooterItem.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/header/LayoutHeader.vue')['default']
    LayoutHeaderGithubButton: typeof import('./src/components/layout/header/LayoutHeaderGithubButton.vue')['default']
    LayoutHeaderLogo: typeof import('./src/components/layout/header/LayoutHeaderLogo.vue')['default']
    LayoutHeaderNavigation: typeof import('./src/components/layout/header/LayoutHeaderNavigation.vue')['default']
    LayoutHeaderSearchBox: typeof import('./src/components/layout/header/LayoutHeaderSearchBox.vue')['default']
    LayoutSider: typeof import('./src/components/layout/LayoutSider.vue')['default']
  }
}

export { }
